### ISSUE TITLE
Move all files inside a "/template" folder

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar-template-meteor#10]
Hi @mwarren2 ,

All content from this template needs to be moved inside a "/template" folder to match Quasar CLI specifications regarding Quasar starter kits. Currently it breaks the CLI when trying to generate the template.

I can do this myself if you want to. If not, take a look at root folder in any other Quasar template repos please.

Thanks for all your hard work!

-Razvan

**Comment by mwarren2** [comment]
@rstoenescu I'll take a look at it later today. There's another issue to be responded to, so I'll do that as well.

**Comment by mwarren2** [comment]
@rstoenescu Not sure this is going to work.
If you'd like to do the move, I'll check afterwards, but I have my doubts.

I've never even looked at Quasar CLI - because Meteor has its own build system, without which it will not work.
Don't know if you remember, but Meteor has no webpack. It was avoided from the start by the Meteor's creators because it's complex.

I think we have two build systems that will not play together. As a Meteor developer I have had no need for Quasar CLI, or rather I have avoided it because I know that it will not play with Meteor.

Is this actually a problem?

**Comment by rstoenescu** [comment]
@mwarren2 This enables Quasar CLI to just generate a folder with all contents from "/template" folder. So it won't interfere in any way with what you created here.

As for the build itself, "quasar dev" runs "npm run dev" and "quasar build" runs "npm run build" commands. But don't worry about these. All that counts is that we have this "/template" folder which is perfectly equivalent to generating a project folder with the current file structure that you have.

**Comment by rstoenescu** [comment]
For example, take a look at https://github.com/quasarframework/quasar-template-default
Notice that when generating a project folder with this template, the contents of the new folder is what "/template" contains. The rest of the files there in root are just "meta" data about the template.

**Comment by mwarren2** [comment]
I've moved everything to a 'template' root folder.
Please check all is Ok.

I will now be trying quasar-framework 14 with Meteor.
If there are problems, I'll write in the starter kit forum page.

**Comment by rstoenescu** [comment]
Yes, everything is good now. Thanks. Closing this. There's the another issue opened for Quasar v0.14. Let's continue there. Let me know if you need the commonjs format of Quasar, as Q v0.14 only has ES6 format available.

**Comment by mwarren2** [comment]
@rstoenescu Hope you saw my comment in the other issue.

Meteor uses the common.js format, so yes, I think that would solve the other issue.
