### ISSUE TITLE
[Request] Improve integration with Meteor

### ISSUE THREAD

**Issue by alexandesigner** [quasarframework/quasar-template-meteor#14]
@rstoenescu @mwarren2

I've worked the standalone integration in this [repository](https://github.com/alexandesigner/quasar-meteor) and it's working fine, take a look and let me know if you have any questions. 
### An alternative

There are two ways we can work with this integration:

1) [This repository](https://github.com/quasarframework/quasar-template-meteor) the Meteor base and integrate the Quasar Framework using the [Meteor + Vue](https://github.com/meteor-vue/vue-meteor)

..and

2) [Use](https://github.com/alexandesigner/quasar-meteor) the Quasar base with webpack and integrate the meteor as a server-side abstraction using the [meteor-client-bundler](https://github.com/Urigo/meteor-client-bundler) it's a client-side meteor.

I would like to help you maintain this integration with meteor. I'm using from version 0.14 in my projects standalone and now integrating with Meteor in some others.

**Comment by mwarren2** [comment]
That's fine by me if you want to try the alternative. I'll look at anything that can keep Meteor working with Quasar.

However I will continue to work here on a solution without webpack, since the Meteor Development Group has always decided to do without it to keep things simple, and I personally have no great wish to learn webpack if I can avoid it.

@rstoenescu has kindly offered to produce a commonjs distribution for quasar in npm (for Quasar 0.14 it should arrive any time), - hopefully until Meteor (I believe in 1.6) will make it even easier to work with npm. Once the commonjs distribution arrives for Quasar 0.14, working with Meteor will involve not much more that a simple install from npm.

**Comment by alexandesigner** [comment]
Excellent! this was my idea to keep both versions .. So both the users of the quasar and the users of the Meteor that are migrating to Vue as their user interface, could choose which one I would like to start.

@mwarren2 I am adept the structure of Meteor also do not have as much experience so with webpack, however, Quasar uses its base in webpack and I just thought it could be easier for Quasar Standalone users to use its structure as it is today.

So how exactly could we make these official alternatives? we would have another repository or we could take advantage of both structures in the same repository, my concern is about CLI, anyway... Let me know how we can do this work.

**Comment by devarthurribeiro** [comment]
#17 @alexandesigner

**Comment by alexandesigner** [comment]
The integration is excellent, I will close this question in favor of keeping it
