### ISSUE TITLE
Temporary solution to use the latest quasar version.

### ISSUE THREAD

**Issue by devarthurribeiro** [quasarframework/quasar-template-meteor#17]
I have implemented a Meteor package containing the 0.15.0 version code built already tested with the template and being fired, could make a pull request with the change while version 0.15.0 is not officially released. I am willing to update and document any change. Is this viable at the moment or is it better to wait for the official version of the quasar?

**Comment by mwarren2** [comment]
If you would like to leave a link here to the package (leave it in the main thread), please do.
I think many people would welcome it. Though maybe you should point out that 0.15 is not yet officially released.

However we need a more permanent solution and I can't be happy with anything less than a simple `npm install`, which is the direction meteor is going, in theory.

I appreciate that we are all finding the wait frustrating - I'm still using 0.13 - and it appears that interest from Meteor users in Quasar is high. However there are two potential solutions to the npm problem still on the cards (Meteor 1.6.1 being one of them), so we need to hold out for a little longer.

**Comment by devarthurribeiro** [comment]
I already created the repository with the package. we really have to be grateful.

**Comment by mwarren2** [comment]
Since you mentioned version quasar 15.0: I see that a **UMD version** of the quasar code is on the [quasar roadmap](http://forum.quasar-framework.org/topic/815/quasar-v0-15-roadmap/2) for 15.0, which should solve the problem for meteor builds with **npm install**.

> The next version (v0.15) will probably be the last before final v1.0. Presenting you with some highlights of v0.15 (new features may be added):

> Major new features

> New 5* premium starter kit
> UMD version

**Comment by devarthurribeiro** [comment]
exactly was the UMD build I used for the package.

**Comment by mwarren2** [comment]
@devarthurribeiro Perhaps I did not understand your original comment.

Would you like to do a pull request? If you have it working with 0.15 beta that would be good.

**Comment by devarthurribeiro** [comment]
@mwarren2 I sorry my english is bad. At the moment I'm using a meteor package that uses the built quasar 0.15. If you want I can add the package to the template and make the migration to quasar 0.15 and I help keep it updated or we can improve the meteor package and organize the repository. 
what do you think ?

**Comment by mwarren2** [comment]
Ok, thanks. I'm going to take a look at the current state of things, because things have moved forward a little bit. Then I'll get back to you.

quasar-framework@0.15.0-beta.4 is installing from npm.
And so is meteor@1.6.1-rc.4

But meteor is doing some cutting edge stuff with a Babel 7.0.0 beta in 1.6.1, and that means that meteor packages like the **akryum** ones, which meteor needs to work with vue, are inevitably going to be updating much later.

So I'm going to try Quasar and Meteor with a very simple installation with as few packages as possibile, and see if the es6 .js file in the /dist folder finally works without a error. The UMD .js files unfortunately don't seem to be of much use for meteor as far as I can see. The way forward is to get the es6 version working. It has exports for every Quasar component which means you can cut right down the amount of code you import.

So in the next couple of days I want to have another try to see if the new Meteor 1.6.1 rc build will work with the es6 .js file. If it does then things are looking hopeful for a return to a simple installation. If it doesn't then lets have a look at your package.
How did you get quasar 0.15 working with the package?

**Comment by devarthurribeiro** [comment]
Ok, let's wait. @mwarren2  I cloned the quasar repository and build it then I put the distribution version already transpilida in my package here is https://github.com/devarthurribeiro/quasar-meteor. but I need to update.

this delay in updating the Akryum packages can cause any problems for our projects?

**Comment by mwarren2** [comment]
The Akryum packages are fixed at a particular version of Babel so when Meteor 1.6.1 comes out they will have to be updated to work with 1.6.1. They made my update to Meteor 1.6.1 fail.

**Comment by mwarren2** [comment]
Thanks to your brilliant idea about transpiling, Arthur, I seem to have got a good result for quasar 14.7 (and probably 15). It should also be a simple clone from github and install from npm.

I hope to finish everything by this evening, watch this space and thanks again for your help!

**Comment by devarthurribeiro** [comment]
@mwarren2 Good thing you got it with version 14.07. because I tried it before and it did not work. If you need help just talk.

**Comment by mwarren2** [comment]
Hi, please check issue #12.
I have updated the code and the install is pretty simple. But there is a ui issue, which hopefully will be solved asap.
