### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by antoninadert** [quasarframework/quasar-template-meteor#18]
On Windows 10, in the bash, I tried

`meteor npm install`
and I got 

```
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/meteor/readable-stream.git
npm ERR!
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR! exited with error code: 128
```

I am pretty sure this is something wih the symlink not working on windows

**Comment by mwarren2** [comment]
Take a look at this:
https://github.com/meteor/meteor/issues/9247

It looks like the problem was the same.

**Comment by antoninadert** [comment]
Thanks for your help. I managed this problem by doing a fresh install (getting rid of node_module)

Now my problem is that I get `'mv' is not recognized as an internal or external command,
operable program or batch file.`

I found this: 
https://stackoverflow.com/questions/23118387/cmd-in-windows-7-does-not-execute-command-python-django

Do you think it means we need a special build command for windows?

**Comment by mwarren2** [comment]
Ok, instead of running 
`npm run transpile`

You will need to take the four commands in package.json under `transpile` and work out how to run them in windows.... You could run the four commands manually.

`"transpile": "mv './.babelrc.RENAMED' './.babelrc'; babel node_modules/quasar-framework/dist/quasar.ios.esm.js --out-file node_modules/quasar-framework/dist/quasar.ios.common.js; babel node_modules/quasar-framework/dist/quasar.mat.esm.js --out-file node_modules/quasar-framework/dist/quasar.mat.common.js;mv './.babelrc' './.babelrc.RENAMED'"
 `
1) move .babelrc.RENAMED to .babelrc
2) babel node_modules/quasar-framework/dist/quasar.ios.esm.js --out-file node_modules/quasar-framework/dist/quasar.ios.common.js;
3) babel node_modules/quasar-framework/dist/quasar.mat.esm.js --out-file node_modules/quasar-framework/dist/quasar.mat.common.js;
4) move .babelrc back to .babelrc.RENAMED

I have to go out right now, but this is your basically what you need to do.
Sorry if I'm not a windows genius, but maybe we can get there together.

Let me know how you get on, and if possibile send me the four commands, just as you ran them for windows.

**Comment by antoninadert** [comment]
Windows is a mess !!! hahaha. I'm glad. It worked !

I had to replace `babel` by `.\node_modules\.bin\babel` because even if I installed babel globally, windows couldn't find the command

`move .\.babelrc.RENAMED .\.babelrc`

`.\node_modules\.bin\babel node_modules\quasar-framework\dist\quasar.ios.esm.js --out-file node_modules\quasar-framework\dist\quasar.ios.common.js`

`.\node_modules\.bin\babel node_modules\quasar-framework\dist\quasar.mat.esm.js --out-file node_modules\quasar-framework\dist\quasar.mat.common.js`

`move .\.babelrc .\.babelrc.RENAMED`

I have no clue how to do this in an NPM script (Batch file needed?)

**Comment by antoninadert** [comment]
I created a batch file that does the job: attached here

Rename it to `transpile.bat`

[transpile.bat.txt](https://github.com/quasarframework/quasar-template-meteor/files/1794082/transpile.bat.txt)

If you know how to work with npm, but there seems to be a conflict between / and \ between windows and other OSes.

I hope you include this solution in the README and in the project for Windows users. 

See you

**Comment by mwarren2** [comment]
Brilliant!
I’ll include it in the Readme, absolutely

**Comment by mwarren2** [comment]
I have included transpile.bat in the root folder and updated the ReadMe to give a bit of help to Windows users.
I have also included you in the ReadMe. I hope you can cope with the fame.

I think we can close this issue.

**Comment by mwarren2** [comment]
> If you know how to work with npm, but there seems to be a conflict between / and \ between windows and other OSes.

Yes, Linux and similar all have the slash in the opposite direction to Windows

**Comment by antoninadert** [comment]
Challenges that I have no clue how to solve. I don't find a place with the correct information. Some people say that we can use forward slash in npm scripts on windows. 

Well it seems that it doesn't work so good for me. Maybe there's a way though,  but I'm a beginner here :)
