### ISSUE TITLE
Could apply 'SSR'? or another way to set up 'SEO'?

### ISSUE THREAD

**Issue by jinear** [quasarframework/quasar-template-meteor#5]
I tried for a week to set up SEO...

Things I used :
1. Vue2.0 SSR with Meteor WebApp package
2. integration with akryum:vue-ssr
3. Meteor Spiderable package (phantomJS)

All failed.....
'Quasar' does not work.
How do I set up 'SEO'?
I have no idea anymore....
I hope this will be resolved.

**Comment by mwarren2** [comment]
@jinear This isn't really the place to ask about SSR!
However since I faced the same problem I can tell you something about it.

1) I think SSR at the moment is not worth pursuing. It hasn't been solved properly for meteor.
2) PhantomJS is a possibility, but it uses too many resources and will stress your machine.
3) The simple answer to SEO for meteor is here [prerender](https://prerender.io). My site was small so it didn't cost a thing. Check it out, it's very simple to use.

-------------

If quasar isn't working take a look at this closed issue from 2 days ago. It might solve your problem:
https://github.com/quasarframework/quasar-template-meteor/issues/3

**Comment by jinear** [comment]
Thanks for the answer.
As far as I know 'Meteor' has various ways to solve 'SEO' problems.
like <a href="https://atmospherejs.com/nodexpert/iron-router-seo#iron-router-seo">iron-router-seo</a> and like <a href="https://atmospherejs.com/meteorhacks/ssr">meteorhacks:ssr</a> and etc...
If <a href="http://quasar-framework.org/">Quasar Framework</a> apply in <a href="https://github.com/Akryum/vue-meteor/tree/master/packages/vue-ssr">Meteor-Vue-SSR</a>, it seems to be solved ...

Anyway, I'll ask you a few more questions.
1. Does <a href="https://github.com/quasarframework/quasar-template-meteor">quasar-template-meteor</a> work well with <a href="https://prerender.io/">prerender</a>?
2. Do you have plan to merge <a href="https://github.com/quasarframework/quasar-template-meteor">quasar-template-meteor</a> with 'SSR' in the future?

I really like <a href="https://github.com/quasarframework/quasar-template-meteor">quasar-template-meteor</a> and cheer up you.

**Comment by mwarren2** [comment]
quasar-template-meteor is merely trying to find the best way to get the quasar-framework working with meteor. It serves no other purpose.

I really can't help you with SSR, quasar is Client, SSR is Server and is another kettle of fish altogether. I wish you luck with SSR, but no, I won't be dealing with it here.
