### ISSUE TITLE
What do you think about 'quasar-template-meteor' with 'apollo'?

### ISSUE THREAD

**Issue by jinear** [quasarframework/quasar-template-meteor#6]
I succeeded in combining  'quasar-template-meteor' and <a href="https://github.com/Akryum/vue-apollo">vue-apollo</a>.
But I am not sure about it.
Is it really a good choice?
Or <a href="https://github.com/quasarframework/quasar-template-meteor">quasar-template-meteor</a>, is it enough only for itself?
Do you think GraphQL is necessary?
I want to know your opinion.

**Comment by mwarren2** [comment]
My compliments for getting Apollo working. 
I personally haven't yet looked at Apollo. 

This is partly because I like mongo, and I don't need anything else.
Also partly because Apollo maybe still isn't quite ready - in the sense that Meteor with mongo made everything so easy, and Apollo, last time I looked, wasn't quite there yet.

quasar-template-meteor is just a project for getting the quasar framework to work with meteor.
It's not perfect yet, but it works. It will be perfect when it works from npm, which I hope will be soon.
